-- Script pra criar o banco. O Postgres não tem um "create database if not
-- exists", então deixo aqui as duas formas que testei:
--
-- 1) pelo PgAdmin (mais fácil): clicar com o botão direito em "Databases" ->
--    Create -> Database... e digitar o nome: escola_megamente
--
-- 2) pelo terminal (psql): rodar o SELECT abaixo, que só cria se não existir.
--    precisa estar conectado em outro banco (ex.: o próprio postgres).
-- SELECT 'CREATE DATABASE escola_megamente'
-- WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'escola_megamente')\gexec